version: '3'

services:
        db:
                image: mysql:latest
                container_name: mysql
                environment:
                        - MYSQL_DATABASE=emotionDiary
                        - MYSQL_ROOT_PASSWORD=password
                        - TZ=Asia/Seoul
                command:
                        #              - --lower_cate_table_names=1
                        - --character-set-server=utf8mb4
                        - --collation-server=utf8mb4_unicode_ci
                volumes:
                        - ./db:/var/lib/mysql
                ports:
                        - 3306:3306